name: Build and Deploy CV

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    container: danteev/texlive:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compile LaTeX resume
        run: latexmk -pdf main.tex
        working-directory: latex


      - name: Prepare Pages artifact
        run: |
          mkdir -p site/cv
          cp latex/main.pdf site/mrontionov-cv.pdf
          cat <<'HTML' > site/index.html
            <!doctype html>
              <html lang="en">
              <head>
                <meta charset="utf-8" />
                <title>Michail Rontionov</title>
                <meta http-equiv="refresh" content="0; url=mrontionov-cv.pdf" />
              </head>
              <body style="display:flex;justify-content:center;align-items:center;min-height:100vh;background:#fff;">
                <p style="font-family:'Latin Modern Roman', 'Times New Roman', Times, serif; color:#666; font-size:1.3rem;">
                <a href="mrontionov-cv.pdf" style="color:#666;text-decoration:none;">Click here to redirect.</a>
                </p>
              </body>
            </html>
          HTML

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
